version: '3.8'

services:
  lobehub:
    image: hub.xiaosi.cc/ghcr.io/sijinhui/lobehub
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #      args:
    #        USE_CN_MIRROR: true
    platform: linux/amd64
    extra_hosts:
      - "one-hub.xiaosi.cc:172.25.114.28"
    #    networks:
    #      - lobe-chat
    network_mode: host
    #    ports:
    #      - "23210:3210"
    environment:
      - PORT=23210
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 23210 || exit 1"]
      interval: 5s
      timeout: 2s
      start_period: 3s
      retries: 3
#    labels:
#      - "traefik.enable=true"
#      - "traefik.tcp.routers.lobe-tcp.rule=HostSNI(`*`)"
#      - "traefik.tcp.routers.lobe-tcp.entrypoints=tcpservice"  # 改为tcpservice匹配反向代理定义
#      - "traefik.tcp.routers.lobe-tcp.service=lobe-tcp-service"
#      - "traefik.tcp.services.lobe-tcp-service.loadbalancer.server.port=3210"

#  reverse-proxy:
#    image: traefik
#    restart: always
#    platform: linux/amd64
#    command:
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.tcpservice.address=:23210"
##      - "--api.insecure=true"
#      # 优化配置
#      - "--ping.entryPoint=tcpservice"
#      - "--providers.docker.network=lobe-chat"
#      # 热加载和更新配置
#      - "--providers.docker.watch=true"
#    ports:
#      - "23210:23210"
##      - "8080:8080"
#    networks:
#      - lobe-chat
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

#networks:
#  lobe-chat: {}
